//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainCommander.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mh-fileserver\\ids$\\kwalker\\pcNameList\\")]
        public string pcListPath {
            get {
                return ((string)(this["pcListPath"]));
            }
            set {
                this["pcListPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OU {
            get {
                return ((string)(this["OU"]));
            }
            set {
                this["OU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com")]
        public string finalDomainComponent {
            get {
                return ((string)(this["finalDomainComponent"]));
            }
            set {
                this["finalDomainComponent"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AKA-ITSUPPORT\\DOMAINCOMMANDER;Initial Catalog=IDSpcNames;Integrated S" +
            "ecurity=True")]
        public string pcNamesConnectionString {
            get {
                return ((string)(this["pcNamesConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c$")]
        public string cshare {
            get {
                return ((string)(this["cshare"]));
            }
            set {
                this["cshare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d$")]
        public string dshare {
            get {
                return ((string)(this["dshare"]));
            }
            set {
                this["dshare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e$")]
        public string eshare {
            get {
                return ((string)(this["eshare"]));
            }
            set {
                this["eshare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.akaheadstart.org")]
        public string mailServer {
            get {
                return ((string)(this["mailServer"]));
            }
            set {
                this["mailServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>\\\\adm-fs\\redirect\\</string>\r\n  <string>\\\\adm-fs\\redirect2\\</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection desktopLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["desktopLocations"]));
            }
            set {
                this["desktopLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>\\\\adm-fs\\redirect\\</string>\r\n  <string>\\\\adm-fs\\redirect2\\</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection documentsLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["documentsLocations"]));
            }
            set {
                this["documentsLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("headstart")]
        public string domain {
            get {
                return ((string)(this["domain"]));
            }
            set {
                this["domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Disabled Accounts,DC=headstart,DC=admin")]
        public string disabledUsersOU {
            get {
                return ((string)(this["disabledUsersOU"]));
            }
            set {
                this["disabledUsersOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>helpdesk@akaheadstart.org</string>
  <string>phigginson@akaheadstart.org</string>
  <string>itspecialists@akaheadstart.org</string>
  <string>hr@akaheadstart.org</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection terminateEmailList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["terminateEmailList"]));
            }
            set {
                this["terminateEmailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Admin</string>
  <string>CasaDeOro</string>
  <string>Darnall</string>
  <string>Farragut</string>
  <string>Granada</string>
  <string>Grand</string>
  <string>LaMesa</string>
  <string>Marilla</string>
  <string>Redwood</string>
  <string>Rolando</string>
  <string>SanMartin</string>
  <string>SanMiguel</string>
  <string>SpringStreet</string>
  <string>VistaLaMesa</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ADLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ADLocations"]));
            }
            set {
                this["ADLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Teachers</string>
  <string>Teachers Assistants</string>
  <string>IT Specialists</string>
  <string>Custodians</string>
  <string>Executive Assistants</string>
  <string>Facilities Technicians</string>
  <string>FCC Supervisors</string>
  <string>FSAs</string>
  <string>Home Visitors</string>
  <string>Office Assistants</string>
  <string>Procurement Specialists</string>
  <string>Program Specialists</string>
  <string>Temporary Employees</string>
  <string>Directors</string>
  <string>CenterDirectors</string>
  <string>Executive Directors</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ADTitles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ADTitles"]));
            }
            set {
                this["ADTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://insite.accuvant.com")]
        public string IntranetSite {
            get {
                return ((string)(this["IntranetSite"]));
            }
            set {
                this["IntranetSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.accuvant.com")]
        public string WebSite {
            get {
                return ((string)(this["WebSite"]));
            }
            set {
                this["WebSite"] = value;
            }
        }
    }
}
